name: 'Build'

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      # - name: Install Dependencies and Build
      #   run: |
      #     npm install
      #     npm run build
      # - name: Archive All Built Files
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: screensaver-card-build
      #     path: dist/
      # - name: Archive graphic
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: graphic/
